package com.rafael;

import javafx.collections.FXCollections;
import javafx.collections.ObservableList;

public class MockDatabase {
    public static ObservableList<Story> getStoriesByFandom(String fandomName) {
        ObservableList<Story> allStories = FXCollections.observableArrayList();

        // K-pop (Added full text as 6th argument)
        allStories.add(new Story("Kpop V8", "User123", "K-pop", "Beat the North Koreans for the world racing title", "Fluff", "Thriller", "Chapter one\n" +
                "18 transporters filed into the pits of the Seoul’s biggest race track for the 2018 South Korean Grand Prix. The crowd in the stands went wild as they saw the transporters at the front of the pits. “Hello everybody,” the commentator screamed into the mic and waved at the camera “I’m James your commentator for this evening and joining me is past race car legend Leetuek from Super junior,” Leetuek smiled at the camera waving. “So, who do you think has a chance at being in the top seven this year, Leetuek?” James asked him. Leetuek smiled “I think every team that is here have a very good chance at being in the top seven this year, because of this there will be a lot more competition on the track today,” he said while they both looked down at the track. With EXO\n“Ok boys time to roll,” a deep voice commanded through out the transporter. Rei yawned from where he was curled up on the coach in the rather large kitchen and lounge room. He slowly stood and stretched his arms before walking to the change rooms where someone was already changing. “nice of you to drop by Rei,” the guy teased as he pulled his uniform over his head. “Shut up Chen,” Rei grumbled with a small smile before he also started changing. “good you’re here Rei, warm ups on the track start soon,” rei turned and faced Junmyeon who was EXO’s main chief.\n" +
                "Rei sighed as Chen started laughing as Junmyeon left “come on Rei the sooner we warm up the sooner were on the track racing,” Chen patted his shoulder. Rei grinned as he finished getting dressed, the two of them ran out of the changing rooms and towards the back of the transport truck. Minseok was already there with Sehun getting the V8 cars ready. Sehun and Minseok turned just as the two racers reached them. “hey Chen, Rei,” Minseok greeted them. Rei nodded and went straight to his car which made Sehun, Chen and Minseok laugh at the racer. “you miss your baby that much Rei,” Sehun teased. Rei looked up at the blonde and smiled “the time is almost here, we get in a spot this year we can go to North Korea and compete with them again,” a deep scowl came onto his face as he thought back to the last three years. They had lost Yifan, Luhan and Tao to injuries in NASCAR, Formula one and Motorcycle grand prix racing. This year it was the V8’s racing and Rei and Chen were looking for revenge. Out of all the teams EXO had lost the most people to injuries and it had seriously hurt them as a team. Minseok looked at the younger in front of him before he wrapped his arms around Rei. When Minseok pulled away Chen came forwards and pulled Rei into a hug as well “come let’s go get ready,” he whispered and pulled the younger into the pits. Sehun and Minseok watched the two go into the pits with fear in their eyes before the went back to setting up the V8’s.\n" +
                "When the two entered you could hear Junmyeon yelled at someone making their way in more they could see that the two trouble makers on the team were looking at the ground in anger. Rei sighed, something had happened when Chen and he had gotten dressed. The two V8 racers watched as Junmyeon yelled curses at what seemed to be the north Korean V8 team that the south Koreans will being going up against next week. Rei walked forwards and looked at the TV where Kyungsoo, Yixing and Kai were watching the north Korean team talk shit about the South Korean team and about EXO specifically. Rei’s jaw clenched and as he stared at the north Koreans team crew chief, that lying snake was the one that had been responsible for all the loses EXO had experienced over the last three years. “Chen get your helmet,” he snapped as he walked past a very angry Junmyeon who was still cursing. Chen looked at Rei confused as the younger stormed past him with helmet in hand to the car that Sehun and Minseok had put out earlier. Rei slammed the door shut and started the engine and speeding out of the pits and onto the track. Junmyeon and the rest of EXO watched in awe as Rei sped around the track. Rei’s hands tightened around the steering wheel as he thought about everything the North Korean team had said about them and done to them. He shot around the corner and punched it speeding past the finish line he slowed down and went back into the pits.\n" +
                "Rei sat there in the car and stared at the steering wheel before he hoped and slammed his door shut. He took his helmet off and looked at the leader board where all the positions were “I don’t believe it Rei from EXO has beaten Bigbang’s Seungri’s time and is now is position one,” the commentator shouted in excitement. Rei turned and looked at Junmyeon who was staring at him along with the rest of the team. Suddenly a big grin spread across Junmyeon’s face, he launched himself at the younger and hugged him tightly. “yes Rei,” Chen laughed as he patted the younger on the back. Rei shook his head before smiling at him “it’s your turn on the track Chen go beat Youngbae,” Rei said smirking making Chen nod his head before going to his V8 and speeding onto the track.\nWith the Commentators\nLeetuek looked at Rei one of the drivers for EXO in amazement “I knew he was good, but not this good.” He told James as he continued to study Rei’s driving. “he reminds me so much of Kyuhyun,” he muttered quietly to himself. “I don’t believe it Rei from EXO has beaten Bigbang’s Seungri’s time and is now in position one,” James shouted from beside him making Leetuek look at him startled before looking at the position board and seeing that Rei had indeed beaten Seungri’s time.“This is going to be an exciting race everyone,” Leetuek nodded and smiled at the camera before looking at James again as he began speaking. “ok the times for every team has been put into a position, EXO’s Rei is leading the race today with Seungri from Bigbang, Minhyuk from Monsta X and Chen from EXO coming in in forth,” there was a large grin on James’s face as he read out the positions. Leetuek looked back at the camera and smiled “now before we start we have to know who the teams are that have made it here today and what will happen when we go to compete next week against the North Koreans.” The last sentence was spoken through gritted teeth. Leetuek himself had a fair share of hard times because of the north Koreans. He had been in a crash with Kyuhyun back when Super Junior had first been formed it had left him with quit a few scars and left Kyuhyun in a coma. The following year though had been a good with Super junior and six other teams beating the North Koreans and going to the World Grand Prix.\n“that’s right Leetuek, for those who don’t know the seven groups that make it up onto the leader board will go to compete against the North Koreans to find out who will represent the whole of Korea either it be North or South,” James said with a big grin. “but it won’t be easy,” Leetuek continued “there are eighteen teams here that will fight for that spot on the leader board and I know that EXO will certainly not let this opportunity pass,” James interrupted Leetuek. Leetuek looked at James with an unamused expression. But James continued anyway “now let’s see EXO background history.”"));

        // Marvel
        allStories.add(new Story("Marvel Cinematic Universe (Abridged)", "DungeonMistress", "Marvel Cinematic Universe", "After the events of Endgame...", "Action, Drama", "Comedy", "Full text of The Stark Legacy..."));

        // Harry Potter
        allStories.add(new Story("Wands and Wizards", "MagicStudent", "Harry Potter", "A new year at Hogwarts begins.", "Magic", "Action","Full text of Wands and Wizards..."));

        return allStories.filtered(s -> s.getFandom().equalsIgnoreCase(fandomName));
    }
}